### PR TITLE
[velero] fixed dnsPolicy position in yaml definition

### PR DESCRIPTION
**Pull request by damoon**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

fixes https://github.com/vmware-tanzu/helm-charts/issues/189

### CODE REVIEW

**Review by zubron — APPROVED** [review]
Thanks for the quick fix!

**Comment by damoon** [comment]
i see there are linters for each PR. why did the linters not find this before me?

**Review by jenting — APPROVED** [review]
Thank you.

**Comment by jenting** [comment]
> why did the linters not find this? see #188

Probably because the CI does not run the test case for `deployRestic: true`.

**Comment by jaredallard** [comment]
My bad, thanks for fixing this! I wrongfully relied on the linters.... My bad.

**Pull request merged**
