### PR TITLE
[velero] Add custom env variables to Restic

### LINKED ISSUE #37: Restic daemon set does not honour extraEnvVars
The Restic daemon set does not use any values set in `.Values.configuration.extraEnvVars`.

This is an issue when running Velero behind a HTTP proxy server, the result is I can backup deployments but not PVs.

The fix is to modify `restic-daemonset.yaml` to include:
```
env:
  {{- with .Values.configuration.extraEnvVars }}
  {{- range $key, $value := . }}
    - name: {{ default "none" $key }}
      value: {{ default "none" $value }}
  {{- end }}
  {{- end }}
```

### PR DESCRIPTION
**Pull request by tobygale**
This fixes #37

### CODE REVIEW

**Comment by tobygale** [comment]
I've just noticed tha tthe indentation in this PR is incorrect.

I'm going to fix it and force-push the branch.

**Comment by cpanato** [comment]
@tobygale can you update your branch?
thanks!

**Comment by cpanato** [comment]
@carlisia as soon you review and you are ok with that, we can merge, I've fixed the chart version

**Comment by tobygale** [comment]
Sorry @cpanato I've been away for a few days, thanks for taking care of that.

**Pull request merged**
