### PR TITLE
[velero] add Prometheus podMonitor custom resource support

### PR DESCRIPTION
**Pull request by arturrez**
Signed-off-by: Artur Reznikov <artur@upbound.io>

### CODE REVIEW

**Comment by jenting** [comment]
Hi @arturrez, thanks for your PR.

But according to #108, we'd like to remove Prometheus operator CRDs.
Therefore, I'd like to close this PR first, but any comments and feedbacks are welcome.

**Comment by arturrez** [comment]
@jenting , thank you for explanation.
Sorry it was my fault, that I didn't check that this functionality existed but was removed before opening PR.

From my personal prospective this approach is not inline with other community helm charts. Majority helm charts for example in https://github.com/helm/charts supports Prometheus CRDs.

Looking into original implementation, I don't think it made a lot of sense to provision ClusterIP Service just to be able to use ServiceMonitor Prometheus CR, that's why I went PodMonitor route.

Anyway, thank you again. Please feel free to reopen my PR in case VMWare changes it's mind around supporting most popular CNCF monitoring system Prometheus.

**Comment by carlisia** [comment]
Let's reconsider this now that wer [reverted the Prhometheus](https://github.com/vmware-tanzu/helm-charts/pull/196) removal.

**Comment by jenting** [comment]
@arturrez hi, we've reverted the Prometheus operator CRDs back, would you like to revisit the PR and resolves the conflicting files? thank you.

**Comment by arturrez** [comment]
I don't think there is a lot of value of switching from ServiceMonitor to PodMonitor after https://github.com/vmware-tanzu/helm-charts/pull/196 was merged.

Please feel free to close it as I don't think my change is really necessary in the current state of things

**Pull request closed without merging**
