### PR TITLE
Fix azure

### LINKED ISSUE #28: Add documentation to values.yaml on how to include secrets
I am installing Velero in K8s cluster that will use Azure Storabe blob as backed, using latest chart version 2.7.5, but I am getting the following error in Velero logs on startup:

```
time="2020-01-02T11:33:46Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:171"
time="2020-01-02T11:33:46Z" level=info msg="Starting Velero server v1.2.0 (5d008491bbf681658d3e372da1a9d3a21ca4c03c)" logSource="pkg/cmd/server/server.go:173"
time="2020-01-02T11:33:46Z" level=info msg="No feature flags enabled" logSource="pkg/cmd/server/server.go:177"
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-microsoft-azure kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2020-01-02T11:33:46Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-microsoft-azure kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2020-01-02T11:33:46Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:337" namespace=velero
time="2020-01-02T11:33:46Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:343" namespace=velero
time="2020-01-02T11:33:49Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:372"
time="2020-01-02T11:33:49Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:406"
time="2020-01-02T11:33:49Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:413"
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = error loading environment from AZURE_CREDENTIALS_FILE (/credentials/cloud): open /credentials/cloud: no such file or directory
```

Here is my valuesfile:

```
##
## Configuration settings that directly affect the Velero deployment YAML.
##

# Details of the container image to use in the Velero deployment & daemonset (if
# enabling restic). Required.
image:
  repository: velero/velero
  tag: v1.2.0
  pullPolicy: IfNotPresent

# Annotations to add to the Velero deployment's pod template. Optional.
#
# If using kube2iam or kiam, use the following annotation with your AWS_ACCOUNT_ID
# and VELERO_ROLE_NAME filled in:
#  iam.amazonaws.com/role: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<VELERO_ROLE_NAME>
podAnnotations: {}

# Resource requests/limits to specify for the Velero deployment. Optional.
resources: {}

# Init containers to add to the Velero deployment's pod spec. At least one plugin provider image is required.
initContainers:
   - name: velero-plugin-for-microsoft-azure
     image: velero/velero-plugin-for-microsoft-azure:v1.0.0
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - name: plugins
         mountPath: /target

# Tolerations to use for the Velero deployment. Optional.
tolerations: []

# Node selector to use for the Velero deployment. Optional.
nodeSelector: {}

# Extra volumes for the Velero deployment. Optional.
extraVolumes:

# Extra volumeMounts for the Velero deployment. Optional.
extraVolumeMounts: []

# Settings for Velero's prometheus metrics. Enabled by default.
metrics:
  enabled: true
  scrapeInterval: 15s

  # Pod annotations for Prometheus
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"

  serviceMonitor:
    enabled: false
    additionalLabels: {}

##
## End of deployment-related settings.
##



##
## Parameters for the `default` BackupStorageLocation and VolumeSnapshotLocation,
## and additional server settings.
##
configuration:
  provider: azure

  # Parameters for the `default` BackupStorageLocation. See
  # https://velero.io/docs/v1.0.0/api-types/backupstoragelocation/
  backupStorageLocation:
    name: azure
    bucket: <redacted>
    prefix: test
    config:
      resourceGroup: <redacted>
      storageAccount: <redacted>

  # These are server-level settings passed as CLI flags to the `velero server` command. Velero
  # uses default values if they're not passed in, so they only need to be explicitly specified
  # here if using a non-default value. The `velero server` default values are shown in the
  # comments below.
  # --------------------
  # `velero server` default: 1m
  backupSyncPeriod: 60m
  # `velero server` default: 1h
  resticTimeout:
  # `velero server` default: namespaces,persistentvolumes,persistentvolumeclaims,secrets,configmaps,serviceaccounts,limitranges,pods
  restoreResourcePriorities:
  # `velero server` default: false
  restoreOnlyMode:

  # additional key/value pairs to be used as environment variables such as "AWS_CLUSTER_NAME: 'yourcluster.domain.tld'"
  extraEnvVars: {}

  # Set log-level for Velero pod. Default: info. Other options: debug, warning, error, fatal, panic.
  logLevel:

  # Set log-format for Velero pod. Default: text. Other option: json.
  logFormat:

##
## End of backup/snapshot location settings.
##



##
## Settings for additional Velero resources.
##

# Whether to create the Velero cluster role binding.
rbac:
  create: true

# Information about the Kubernetes service account Velero uses.
serviceAccount:
  server:
    create: true
    name:

# Info about the secret to be used by the Velero deployment, which
# should contain credentials for the cloud provider IAM account you've
# set up for Velero.
credentials:
  existingSecret: "cloud-credentials"
  useSecret: true

# Wheter to create volumesnapshotlocation crd, if false => disable snapshot feature
snapshotsEnabled: false

# Whether to deploy the restic daemonset.
deployRestic: false

schedules: 
  daily-backup:
    schedule: "0 17 * * *"
    template:
      ttl: "120h"
      excludedNamespaces:
        - global-infrastructure

configMaps: {}

##
## End of additional Velero resource settings.
##
```

And here are the contents of pre-existing secret "cloud-credentials" in the namespace where velero is being installed:
```
apiVersion: v1
data:
  AZURE_CLIENT_ID: <redacted>
  AZURE_CLIENT_SECRET: <redacted>
  AZURE_CLOUD_NAME: <redacted>
  AZURE_RESOURCE_GROUP: <redacted>
  AZURE_SUBSCRIPTION_ID: <redacted>
  AZURE_TENANT_ID: <redacted>
kind: Secret
metadata:
  creationTimestamp: "2020-01-02T11:07:22Z"
  labels:
    CREATED_BY: terraform
  name: cloud-credentials
  namespace: velero
  resourceVersion: "43307401"
  selfLink: /api/v1/namespaces/velero/secrets/cloud-credentials
  uid: 0d031617-2d50-11ea-a618-e29387fbefef
type: Opaque
```

Am I doing anything wrong with my configuration?

### LINKED ISSUE #30: Restic daemon set failed to communicate with Azure provider
In Present helm chart restic-daemonset.yaml obtaining azure credentials from sercret and exposed as environment variable.

          {{- if and .Values.credentials.useSecret (eq $provider "azure") }}
          envFrom:
            - secretRef:
                name: {{ include "velero.secretName" . }}
          {{- end }}

But velero image velero/velero:v1.2.0 expects the credential from  env AZURE_CREDENTIALS_FILE /credentials/cloud

We have to modify the  restic-daemonset.yaml to make it to work,

  {{- if .Values.deployRestic }}
  {{- $provider := .Values.configuration.provider -}}
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
     name: restic
     labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
spec:
  selector:
    matchLabels:
      name: restic
  template:
    metadata:
      labels:
        name: restic
        app.kubernetes.io/name: {{ include "velero.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "velero.chart" . }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.server.create }}
      serviceAccountName: {{ include "velero.serverServiceAccount" . }}
      {{- end }}
      securityContext:
        runAsUser: 0
      {{- if .Values.restic.priorityClassName }}
      priorityClassName: {{ include "velero.restic.priorityClassName" . }}
      {{- end }}
      volumes:
        {{- if .Values.credentials.useSecret }}
        - name: cloud-credentials
          secret:
            secretName: {{ include "velero.secretName" . }}
        {{- end }}
        - name: host-pods
          hostPath:
            path: {{ .Values.restic.podVolumePath }}
        - name: scratch
          emptyDir: {}
        {{- if .Values.restic.extraVolumes }}
        {{- toYaml .Values.restic.extraVolumes | nindent 8 }}
        {{- end }}
      containers:
        - name: velero
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /velero
          args:
            - restic
            - server
          volumeMounts:
            {{- if .Values.credentials.useSecret }}
            - name: cloud-credentials
              mountPath: /credentials
            {{- end }}
            - name: host-pods
              mountPath: /host_pods
              mountPropagation: HostToContainer
            - name: scratch
              mountPath: /scratch
            {{- if .Values.restic.extraVolumeMounts }}
            {{- toYaml .Values.restic.extraVolumeMounts | nindent 12 }}
            {{- end }}
          env:
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            {{- if and .Values.credentials.useSecret (or (eq $provider "aws") (or (eq $provider "gcp") (eq $provider "azure"))) }}
            {{- if eq $provider "aws" }}
            - name: AWS_SHARED_CREDENTIALS_FILE
            {{- else if eq $provider "gcp"}}
            - name: GOOGLE_APPLICATION_CREDENTIALS
            {{- else }}
            - name: AZURE_CREDENTIALS_FILE
            {{- end }}
              value: /credentials/cloud
            {{- end }}
            {{- if eq $provider "minio" }}
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
            {{- end }}
          securityContext:
            privileged: {{ .Values.restic.privileged }}
          {{- with .Values.restic.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.restic.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

### LINKED ISSUE #61: Azure deployment failed because it does not match velero cli installation
I deployed velero on Azure using the helm chart. Everything looks good
```
kubectl get po -n velero 
NAME                      READY   STATUS    RESTARTS   AGE
restic-bjc7m              1/1     Running   0          28m
restic-sz8xw              1/1     Running   0          28m
restic-xhp7w              1/1     Running   0          28m
velero-6b688bdd4c-cjhks   1/1     Running   0          28m
 ```
But while running  `velero backup` command, I'm getting some weird errors as follows:

```time="2020-02-13T14:18:04Z" level=error msg="Error backing up item" backup=velero/ark-test-ns4-1581603471 error="pod volume backup failed: error setting restic cmd env: error getting azure restic env vars: unable to get all required environment variables: the following keys do not have values: AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_SUBSCRIPTION_ID" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:182" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=nginx-deployment-864c87c896-8zfgs namespace=ark-test-ns4-1581603471 resource=pods```

and the problem was the `envFrom` 
```
          {{- if eq $provider "azure" }}
          envFrom:
            - secretRef:
                name: {{ include "velero.secretName" . }}
          {{- end }}
```
Comparing the velero cli installation with the output of helm chart is a bit different concerning the way we use the cloud-credentials 

with veleo cli we don't use the `envFrom` field 
```
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
    namespace: velero
  spec:
    selector:
      matchLabels:
        deploy: velero
    strategy: {}
    template:
      metadata:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8085"
          prometheus.io/scrape: "true"
        creationTimestamp: null
        labels:
          component: velero
          deploy: velero
      spec:
        containers:
        - args:
          - server
          command:
          - /velero
          env:
          - name: VELERO_SCRATCH_DIR
            value: /scratch
          - name: VELERO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LD_LIBRARY_PATH
            value: /plugins
          - name: AZURE_CREDENTIALS_FILE
            value: /credentials/cloud
          image: velero/velero:v1.2.0
          imagePullPolicy: IfNotPresent
          name: velero
          ports:
          - containerPort: 8085
            name: metrics
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
          - mountPath: /plugins
            name: plugins
          - mountPath: /scratch
            name: scratch
          - mountPath: /credentials
            name: cloud-credentials
        initContainers:
        - image: velero/velero-plugin-for-microsoft-azure:v1.0.0
          imagePullPolicy: IfNotPresent
          name: velero-plugin-for-microsoft-azure
          resources: {}
          volumeMounts:
          - mountPath: /target
            name: plugins
        restartPolicy: Always
        serviceAccountName: velero
        volumes:
        - emptyDir: {}
          name: plugins
        - emptyDir: {}
          name: scratch
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
```
Deleting manually it fixes the problem.

### PR DESCRIPTION
**Pull request by jenting**
Fix #28 
Fix #30
Fix #61 

Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>

### CODE REVIEW

**Comment by jenting** [comment]
@skriss @nrb @cpanato PTAL :bowing_man:

**Comment by fredgate** [comment]
Are you sure that it fixes the issue for the Restic daemon set ?
Certainly the environment variable indicating the credentials file is well defined, but for Azure the volume with the secret is neither declared nor mounted in the container.

**Comment by skriss** [comment]
Hmm, it does look like azure needs to be added here: https://github.com/vmware-tanzu/helm-charts/pull/67/files#diff-d73d1b7d88601fa809ff6d07abb57bc3R61

**Comment by fredgate** [comment]
In the Restic daemonset
https://github.com/jenting/helm-charts/blob/437d23d541eb54627105578a01d38a14a1de5fdc/charts/velero/templates/restic-daemonset.yaml
Azure is not managed for the volumes (line 38) and for the volume mounts (line 61).
So now do we really need to test for cloud providers or can we reduce the test to the use of secret ?

**Comment by jenting** [comment]
Oops, thanks @fredgate for the catch up. I missed line 38 and line 61.

**Pull request merged**
