### PR TITLE
[velero]: Feature push new charts to GHCR OCI registry as well

### PR DESCRIPTION
**Pull request by ishuar**
#### Special notes for your reviewer:

closes https://github.com/vmware-tanzu/helm-charts/issues/521

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] ~Chart Version bumped~
- [ ] Variables are documented in the values.yaml or README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Comment by ishuar** [comment]
> If I understand correctly, the helm chart would upload to original helm chart repo as well as the oci://ghcr.io chart repo, correct?

Yes, the current workflow remains the same. 

Someone might need to verify if the [permissions](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility) allow the package to be available publically to work with the OCI registry.

**Comment by jenting** [comment]
> > If I understand correctly, the helm chart would upload to original helm chart repo as well as the oci://ghcr.io chart repo, correct?
> 
> 
> 
> Yes, the current workflow remains the same. 
> 
> 
> 
> Someone might need to verify if the [permissions](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility) allow the package to be available publically to work with the OCI registry. 
> 
> 

@reasonerjt could you help check the permissions mentioned above was enabled for this repo? We would like push helm chart to oci://ghcr.io as well.

**Review by jenting — APPROVED** [review]

**Comment by ywk253100** [comment]
@ishuar @jenting The action job failed with `no such file` error, please check and fix it

**Comment by jenting** [comment]
Interested. I did a fork to my own repo, and the [chart release](https://github.com/jenting/vmware-tanzu-helm-charts/pkgs/container/charts%2Fvelero) successfully. 

@ishuar do you have any idea why?

**Pull request merged**
