### PR TITLE
[velero] fix bug using workload identity issue #161

### PR DESCRIPTION
**Pull request by xUnholy**
Signed-off-by: Michael Fornaro <20387402+xUnholy@users.noreply.github.com>

#### Special notes for your reviewer:

Fixing bug as mentioned in #161 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Review by jenting — DISMISSED** [review]
LGTM, thanks

**Comment by xUnholy** [comment]
Thanks for the swift review @jenting! As this PR requires 2 approvals I'm looping in @carlisia to please also take a look when you have a spare moment.

**Comment by xUnholy** [comment]
@jenting can we bump this PR to get our second approver to fix this bug?

**Comment by jenting** [comment]
> @jenting can we bump this PR to get our second approver to fix this bug?

cc @carlisia @nrb @ashish-amarnath @cpanato

**Review by cpanato — APPROVED** [review]

**Comment by jenting** [comment]
I've help bump the chart version, PTAL @cpanato

**Review by jenting — APPROVED** [review]

**Review by cpanato — APPROVED** [review]

**Pull request merged**
