### PR TITLE
[velero] Add priorityClassName in the values.yaml file to make it 'official'

### PR DESCRIPTION
**Pull request by machine424**
Just to make it official, so we cannot drop it silently.

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Comment by machine424** [comment]
Hello from the other world

**Comment by jenting** [comment]
> Hello from the other world

@machine424 Thanks for your contribution, but I have to read more details about the purpose of the Pod priority class first. Or could you please elaborate more on the issue you met? Thanks.

**Comment by jenting** [comment]
I've helped to bump the Chart version.

**Review by jenting — APPROVED** [review]
LGTM, thanks to @machine424

**Comment by jenting** [comment]
@cpanato @carlisia could you please take a look at this? thank you.

**Review by cpanato — APPROVED** [review]

**Comment by cpanato** [comment]
thanks for your PR!

**Pull request merged**
