### PR TITLE
[velero] EXISTING_SECRET_KEY added existingSecretKey option to mount already d…

### PR DESCRIPTION
**Pull request by iamomi**
…efined keys

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the values.yaml or README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Comment by jenting** [comment]
Thanks for your contribution.

- Could you please describe the problem you met?
- Could [credentials.existingSecret](https://github.com/vmware-tanzu/helm-charts/blob/5395edb/charts/velero/values.yaml#L232) fix the problem you met?

**Comment by carlisia** [comment]
Hey @iamomi. Velero already defaults to a secret with a key `cloud`. Why do you need this change?

**Comment by jenting** [comment]
Ping @iamomi

**Comment by jenting** [comment]
Close it as it's not active and we don't know the user's use case.
Feel free to reopen it.

**Pull request closed without merging**
