### PR TITLE
Allow independent backup/snapshot providers

### PR DESCRIPTION
**Pull request by yurinnick**
- Allow setting different providers for backup/snapshot locations
- Support freeform location configuration to enable 3ed-party providers (OpenEBS, Ceph etc)
- Fix location name setup

[Test output](https://gist.github.com/yurinnick/73beca92c8cf4b72c3d0eb3119456d42)

Signed-off-by: Nikolai Iurin <yurinnick93@gmail.com>

### CODE REVIEW

**Comment by yurinnick** [comment]
Related to #75 #77

**Comment by kenperkins** [comment]
I'd love to see this as an option: we have some situations where we want to use S3 api (on ceph) but still use cinder (backed by ceph) for volume snapshots. What do we need to get the merge conflict resolved and get a review on this issue?

**Comment by yurinnick** [comment]
Can we get it reviewed please? @carlisia

**Comment by nrb** [comment]
@yurinnick Could you please rebase on master? The code looks good to me!

**Pull request merged**
