### PR TITLE
quote extraEnvVars to support special chars

### PR DESCRIPTION
**Pull request by tareqhs**

### CODE REVIEW

**Comment by tareqhs** [comment]
@jenting , please review

**Comment by jenting** [comment]
Please also consider `restic-daemonset.yaml`
https://github.com/vmware-tanzu/helm-charts/blob/85e95d3/charts/velero/templates/restic-daemonset.yaml#L76-L77

**Comment by tareqhs** [comment]
@jenting - done, please review

**Comment by carlisia** [comment]
@tareqhs thanks for this. Before I request a second approval, pls rebase when you have a chance.

**Comment by carlisia** [comment]
Hi @tareqhs, please bump the chart version when you have a chance, thank you. 🙏

**Comment by tareqhs** [comment]
@carlisia done

**Pull request merged**
