### PR TITLE
[velero] A one time job to install/upgrade/delete CRDs

### LINKED ISSUE #44: Drop CRDs manifest but install CRDs by velero install
Right now, the velero helm chart CRD manifest is not in-sync with velero repo.
Also the command `velero install --crds-only` supports install CRDs.

I'm wondering that is it better to drop helm-chart CRDs manifest but install the CRDs by `veleror install --crds-only`?
This way makes maintaining the CRDs from the single source and does not need to address sync CRD manifest from velero repo to velero helm chart.

Are there any other cons I did not think about? Thanks.

### PR DESCRIPTION
**Pull request by jenting**
#### Special notes for your reviewer:

Use a one time job to install/upgrade/delete CRDs with the corresponding service account and RBAC.

With this PR:
- we don't have to manage the CRDs manifests in code and check it in sync with https://github.com/vmware-tanzu/velero repo
- we could make sure that the helm upgrade will upgrade the CRDs, please ref to https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

fixes #44 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Comment by jenting** [comment]
@carlisia @nrb @ashish-amarnath  PTAL

**Review by cidsasaki — APPROVED** [review]

**Review by carlisia — CHANGES_REQUESTED** [review]
@jenting please rebase and bump up the chart version.

I tested this and it's looking good!

**Comment by carlisia** [comment]
I installed this chart with both Helm 3 and Helm 3, and it seems that it all works!

Also, setting `installCRDs=false` does not load the CRDs with both Helm versions. 👍

This is what the top part of a Velero CRD looks like when it's generated by main vs this branch, for each of the Helm versions:

1. Helm 3, main branch:
```
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: "2020-12-16T23:01:14Z"
  generation: 1
  labels:
    app.kubernetes.io/name: velero
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1beta1
    fieldsType: FieldsV1
```

2. Helm 3, this branch:
```
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"controller-gen.kubebuilder.io/version":"v0.3.0"},"creationTimestamp":null,"labels":{"component":"velero"},"name":"backupstoragelocations.velero.io"},"spec":{"additionalPrinterColumns":[{"JSONPath":".status.phase","description":"Backup Storage Location status such as Available/Unavailable","name":"Phase","type":"string"},{"JSONPath":".status.lastValidationTime","description":"LastValidationTime is the last time the backup store location was validated","name":"Last Validated","type":"date"},{"JSONPath":".metadata.creationTimestamp","name":"Age","type":"date"}],"group":"velero.io","names":{"kind":"BackupStorageLocation","listKind":"BackupStorageLocationList","plural":"backupstoragelocations","shortNames":["bsl"],"singular":"backupstoragelocation"},"preserveUnknownFields":false,"scope":"Namespaced","subresources":{"status":{}},"validation":{"openAPIV3Schema":{"description":"BackupStorageLocation is a location where Velero stores backup objects","properties":{"apiVersion":{"description":"APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources","type":"string"},"kind":{"description":"Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds","type":"string"},"metadata":{"type":"object"},"spec":{"description":"BackupStorageLocationSpec defines the desired state of a Velero BackupStorageLocation","properties":{"accessMode":{"description":"AccessMode defines the permissions for the backup storage location.","enum":["ReadOnly","ReadWrite"],"type":"string"},"backupSyncPeriod":{"description":"BackupSyncPeriod defines how frequently to sync backup API objects from object storage. A value of 0 disables sync.","nullable":true,"type":"string"},"config":{"additionalProperties":{"type":"string"},"description":"Config is for provider-specific configuration fields.","type":"object"},"objectStorage":{"description":"ObjectStorageLocation specifies the settings necessary to connect to a provider's object storage.","properties":{"bucket":{"description":"Bucket is the bucket to use for object storage.","type":"string"},"caCert":{"description":"CACert defines a CA bundle to use when verifying TLS connections to the provider.","format":"byte","type":"string"},"prefix":{"description":"Prefix is the path inside a bucket to use for Velero storage. Optional.","type":"string"}},"required":["bucket"],"type":"object"},"provider":{"description":"Provider is the provider of the backup storage.","type":"string"},"validationFrequency":{"description":"ValidationFrequency defines how frequently to validate the corresponding object storage. A value of 0 disables validation.","nullable":true,"type":"string"}},"required":["objectStorage","provider"],"type":"object"},"status":{"description":"BackupStorageLocationStatus defines the observed state of BackupStorageLocation","properties":{"accessMode":{"description":"AccessMode is an unused field. \n Deprecated: there is now an AccessMode field on the Spec and this field will be removed entirely as of v2.0.","enum":["ReadOnly","ReadWrite"],"type":"string"},"lastSyncedRevision":{"description":"LastSyncedRevision is the value of the `metadata/revision` file in the backup storage location the last time the BSL's contents were synced into the cluster. \n Deprecated: this field is no longer updated or used for detecting changes to the location's contents and will be removed entirely in v2.0.","type":"string"},"lastSyncedTime":{"description":"LastSyncedTime is the last time the contents of the location were synced into the cluster.","format":"date-time","nullable":true,"type":"string"},"lastValidationTime":{"description":"LastValidationTime is the last time the backup store location was validated the cluster.","format":"date-time","nullable":true,"type":"string"},"phase":{"description":"Phase is the current state of the BackupStorageLocation.","enum":["Available","Unavailable"],"type":"string"}},"type":"object"}},"type":"object"}},"version":"v1","versions":[{"name":"v1","served":true,"storage":true}]}}
  creationTimestamp: "2020-12-16T22:50:21Z"
  generation: 1
  labels:
    component: velero
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
```

3. Helm 2, main branch:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  creationTimestamp: "2020-12-16T22:12:26Z"
  generation: 1
  labels:
    app.kubernetes.io/name: velero
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1beta1
    fieldsType: FieldsV1
```

Helm 2, this branch:
```
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{"controller-gen.kubebuilder.io/version":"v0.3.0"},"creationTimestamp":null,"labels":{"component":"velero"},"name":"backupstoragelocations.velero.io"},"spec":{"additionalPrinterColumns":[{"JSONPath":".status.phase","description":"Backup Storage Location status such as Available/Unavailable","name":"Phase","type":"string"},{"JSONPath":".status.lastValidationTime","description":"LastValidationTime is the last time the backup store location was validated","name":"Last Validated","type":"date"},{"JSONPath":".metadata.creationTimestamp","name":"Age","type":"date"}],"group":"velero.io","names":{"kind":"BackupStorageLocation","listKind":"BackupStorageLocationList","plural":"backupstoragelocations","shortNames":["bsl"],"singular":"backupstoragelocation"},"preserveUnknownFields":false,"scope":"Namespaced","subresources":{"status":{}},"validation":{"openAPIV3Schema":{"description":"BackupStorageLocation is a location where Velero stores backup objects","properties":{"apiVersion":{"description":"APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources","type":"string"},"kind":{"description":"Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds","type":"string"},"metadata":{"type":"object"},"spec":{"description":"BackupStorageLocationSpec defines the desired state of a Velero BackupStorageLocation","properties":{"accessMode":{"description":"AccessMode defines the permissions for the backup storage location.","enum":["ReadOnly","ReadWrite"],"type":"string"},"backupSyncPeriod":{"description":"BackupSyncPeriod defines how frequently to sync backup API objects from object storage. A value of 0 disables sync.","nullable":true,"type":"string"},"config":{"additionalProperties":{"type":"string"},"description":"Config is for provider-specific configuration fields.","type":"object"},"objectStorage":{"description":"ObjectStorageLocation specifies the settings necessary to connect to a provider's object storage.","properties":{"bucket":{"description":"Bucket is the bucket to use for object storage.","type":"string"},"caCert":{"description":"CACert defines a CA bundle to use when verifying TLS connections to the provider.","format":"byte","type":"string"},"prefix":{"description":"Prefix is the path inside a bucket to use for Velero storage. Optional.","type":"string"}},"required":["bucket"],"type":"object"},"provider":{"description":"Provider is the provider of the backup storage.","type":"string"},"validationFrequency":{"description":"ValidationFrequency defines how frequently to validate the corresponding object storage. A value of 0 disables validation.","nullable":true,"type":"string"}},"required":["objectStorage","provider"],"type":"object"},"status":{"description":"BackupStorageLocationStatus defines the observed state of BackupStorageLocation","properties":{"accessMode":{"description":"AccessMode is an unused field. \n Deprecated: there is now an AccessMode field on the Spec and this field will be removed entirely as of v2.0.","enum":["ReadOnly","ReadWrite"],"type":"string"},"lastSyncedRevision":{"description":"LastSyncedRevision is the value of the `metadata/revision` file in the backup storage location the last time the BSL's contents were synced into the cluster. \n Deprecated: this field is no longer updated or used for detecting changes to the location's contents and will be removed entirely in v2.0.","type":"string"},"lastSyncedTime":{"description":"LastSyncedTime is the last time the contents of the location were synced into the cluster.","format":"date-time","nullable":true,"type":"string"},"lastValidationTime":{"description":"LastValidationTime is the last time the backup store location was validated the cluster.","format":"date-time","nullable":true,"type":"string"},"phase":{"description":"Phase is the current state of the BackupStorageLocation.","enum":["Available","Unavailable"],"type":"string"}},"type":"object"}},"type":"object"}},"version":"v1","versions":[{"name":"v1","served":true,"storage":true}]}}
  creationTimestamp: "2020-12-16T22:14:13Z"
  generation: 1
  labels:
    component: velero
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
```

**Comment by carlisia** [comment]
I wanted people to look at those CRs and double check that we are not missing any Helm specific annotation. c/c @cpanato / @nrb.

**Comment by carlisia** [comment]
@jenting is there a way to delete the CRDs when unintalling Helm? If so, it should be done in a separate PR but bringing it up now in case this way of installing the CRDs would preclude that. Just in case.

**Review by carlisia — CHANGES_REQUESTED** [review]
@jenting the CRDs in this project would have to be deleted.

**Review by carlisia — CHANGES_REQUESTED** [review]
~~@jenting if it's not asking too much, please add, under both Helm 3 and Helm 2 instructions:~~

 ~~The line that says:~~
~~"Note: you may add the flag --set installCRDs=false if you don't want to install the CRDs."~~

~~Please make it:~~

~~"Note: you may add the flag `--set installCRDs=false` if you don't want to install the CRDs.~~

~~Likewise, you may add the flag --set `cleanUpCRDs=true` if you want to delete the Velero CRDs after deleting a release. Please note that cleaning up CRDs will also delete any CRD instance, such as BackupStorageLocation and VolumeSnapshotLocation, which would have to be reconfigured when reinstalling Velero. The backup data in object storage will _not_ be deleted, even though the backup instances in the cluster will.~~

This was changed and merged in a separate PR. Thank you!

**Comment by jenting** [comment]
@carlisia Thank you for the detailed review and comments, but I'd like to double verify the PR to verify it works on modern GitOps tools like ArgoCD or Flux because these would ignore the helm annotation `"helm.sh/hook": post-install,post-upgrade`.

**Comment by carlisia** [comment]
>  I'd like to double verify the PR to verify it works on modern GitOps tools like ArgoCD or Flux

@jenting to clarify: do you have a way to test this? No rush, just wanted to know if you have the resources or if we should look for people in the community who could help.

**Comment by jenting** [comment]
The issues I would like to solve are:
1. Fix helm upgrade issue, helm does not performs upgrade CRDs during `helm upgrade`.
2. Avoids the manually sync CRDs on each Velero release.

However, from the Github issue, the community users would like to see the CRDs manifest by `helm template --include-crds`. With this PR's approach, we could not achieve it since the CRDs are package inside Velero CLI, so the users can't display  CRDs manifest directly.

Therefore, I'd like to close this PR and focus on fix issue 1 only.
From the [helm doc CRDs best practice](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/), we should separate the helm CRDs into another chart. After that, we'll have 2 charts for Velero, one is CRDs only, the other one is Velero deployment.
Then, the user has to install/upgrade CRDs chart first and then Velero deployment.

What do others think? @carlisia @nrb @cpanato

**Comment by carlisia** [comment]
@jenting I'm not against having a separate chart for the CRDs, as long as that doesn't mean replicating things around.

I like the idea of closing this and focusing on only the upgrade issue.

Before you do the PR though, please open an issue and explain:

- how would an install and upgrade look like for using `helm install`, template, and gitops tools that don't use `helm install`, for each Helm 2 and Helm 3.

- how would that be different than what we have now, and why would it be better?

I read the docs and some discussions, what I got was how to do things one way or another, but not much the tradeoff and comparison between the different ways, other than the general "this sucks".

Thank you!

**Comment by jenting** [comment]
Close the PR because we wrapper the way to install/upgrade CRDs by the `velero install --crds-only --dry-run -oyaml`, this makes `helm template` display the CRDs manifest not work anymore.

**Pull request closed without merging**
