### PR TITLE
Fix spacing within curly braces

### PR DESCRIPTION
**Pull request by calvinbui**
Fix spacing within curly braces

Signed-off-by: Calvin Bui <3604363+calvinbui@users.noreply.github.com>

### CODE REVIEW

**Comment by cpanato** [comment]
thanks for your contribution @calvinbui 
can you please bump the chart version and also sign the DCO?

**Comment by carlisia** [comment]
Looks good after the version bump and DCO!

**Comment by calvinbui** [comment]
done and ready for re-review

**Comment by carlisia** [comment]
Oh oh @calvinbui, this PR needs another version bump.

**Pull request merged**
