### PR TITLE
[velero] Bump velero version v1.5.3

### PR DESCRIPTION
**Pull request by jenting**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the values.yaml or README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Comment by jenting** [comment]
@cpanato I rebased the code to the main branch, but the helm2 still points to the legacy helm chart URL. Do you know why?

**Comment by cpanato** [comment]
@jenting will take a look

**Comment by jenting** [comment]
> @jenting will take a look

https://github.com/vmware-tanzu/helm-charts/runs/1720913978
Seems like the helm2 CI lint does not run the check :confused:

**Review by carlisia — APPROVED** [review]
👍

**Review by cpanato — APPROVED** [review]
thanks!

**Pull request merged**
