### PR TITLE
[velero] Adding imagePullSecrets to the chart

### PR DESCRIPTION
**Pull request by arminc**
Signed-off-by: Armin <armin@coralic.nl>

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Review by jenting — APPROVED** [review]
LGTM, thanks.

**Comment by jenting** [comment]
@carlisia PTAL

**Comment by carlisia** [comment]
This looks good but it needs a version bump now, please.

**Review by jenting — APPROVED** [review]

**Comment by jenting** [comment]
@carlisia I've help bump the version, please take a look.

**Comment by arminc** [comment]
My apologies, I forgot to do that. Thank you @jenting

**Review by carlisia — APPROVED** [review]
👍

**Pull request merged**
