### PR TITLE
[velero] Add version label to deployment

### PR DESCRIPTION
**Pull request by wyattfry**
#### Special notes for your reviewer:
This PR adds the Kubernetes-recommended label "app.kubernetes.io/version" to the Deployment and its Pods.
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

The value of the version label:

> The current version of the application (e.g., a [SemVer 1.0](https://semver.org/spec/v1.0.0.html), revision hash, etc.)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped, please refer to the [chart version instruction](https://github.com/vmware-tanzu/helm-charts/blob/main/RELEASE-INSTRUCT.md#guidelines)
- [x] Variables are documented in the values.yaml or README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Review by jenting — APPROVED** [review]
lgtm

**Comment by wyattfry** [comment]
@aramprice @weseven could i please have one more review?

**Comment by aramprice** [comment]
@wyattfry - you may have tagged the wrong person, I don't have context on this codebase.

**Review by ywk253100 — APPROVED** [review]

**Comment by wyattfry** [comment]
> @wyattfry - you may have tagged the wrong person, I don't have context on this codebase.

Ah, sorry about that

**Pull request merged**
