### PR TITLE
[velero]: add template for generating node-agent with prefix of release name 

### PR DESCRIPTION
**Pull request by 1602077**
#### Special notes for your reviewer:

When installing velero as a part of an umbrella helm the node-agent daemonset name does not respect the helm release name as it is hard coded in the template definition. 

This makes the lineage of the `node-agent` daemonset unclear.

i.e.
```bash
$ kubectl get po -n my-release -o name
pod/my-release-velero-b5c66b7d6-lj6l9
pod/node-agent-bqf78
```

This PR adds a template which prefixes the release name on the `node-agent` daemonset to be consistent with the velero deployment naming scheme

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped, please refer to the [chart version instruction](https://github.com/vmware-tanzu/helm-charts/blob/main/RELEASE-INSTRUCT.md#guidelines)
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Review by jenting — APPROVED** [review]
LGTM

**Comment by 1602077** [comment]
apologies @jenting - had to re-push to fix a mistake I made in copying over from one of the other templates - should be all good to go now. cheers

**Comment by jenting** [comment]
Could you help resolve the conflict, thanks.

**Review by jenting — APPROVED** [review]

**Comment by ywk253100** [comment]
@1602077 @jenting Currently, the Velero code uses the hardcoded  names of Velero deployment and Node Agent daemonset to do some checking (e.g. checking whether node-agent is starting up before doing the file system backup), changing the names will break these features.
@1602077 Suggest open an issue in the Velero repository first if this is reasonable requirement for you

**Comment by 1602077** [comment]
@ywk253100 okay - cheers for the update. Will close this one out for now then.

**Pull request closed without merging**
