### PR TITLE
Add LD_LIBRARY_PATH to deployment

### PR DESCRIPTION
**Pull request by c3y1huang**
This already merged to velero in https://github.com/vmware-tanzu/velero/pull/1893. 
Make helm chart deployment consistent and able to use for vsphere plugin.

Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>

### CODE REVIEW

**Comment by c3y1huang** [comment]
rebased.

**Comment by c3y1huang** [comment]
rebased.

**Comment by cpanato** [comment]
@nrb PTAL and can merge it :)
I've bumped the chart version

**Comment by c3y1huang** [comment]
Rebased.

Current `Test Charts` is failing due to #85.

**Comment by c3y1huang** [comment]
ref: https://github.com/SUSE/avant-garde/issues/1221

**Pull request merged**
