### PR TITLE
fix: custom CA not working

### LINKED ISSUE #121: Implement custom CA for BackupStorageLocation
Following https://github.com/vmware-tanzu/velero/issues/1027 / https://github.com/vmware-tanzu/velero/issues/2330 / https://github.com/vmware-tanzu/velero/issues/2332 / https://github.com/vmware-tanzu/velero/issues/2333

Please adapt the Helm chart to allow setting a custom CA bundle in the BackupStorageLocation

### PR DESCRIPTION
**Pull request by jenting**
fixes #121 

Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>

### CODE REVIEW

**Comment by nrb** [comment]
Looks like this needs a rebase

**Comment by carlisia** [comment]
Rebase done.

**Comment by jenting** [comment]
The rebase action outputs :thinking: 

> refusing to allow a GitHub App to create or update workflow `.github/workflows/rebase.yml` without `workflows` permission`

**Comment by carlisia** [comment]
> lint-test Expected — Waiting for status to be reported

What does this mean?

**Comment by jenting** [comment]
> > lint-test Expected — Waiting for status to be reported
> 
> What does this mean?

Something wrong with Github action, it did not trigger lint-test action :thinking: 
Let me reopen the PR to retrigger it.

**Comment by jenting** [comment]
@nrb @ashish-amarnath @cpanato PTAL

**Pull request merged**
