### PR TITLE
RBAC: fix file name.

### PR DESCRIPTION
**Pull request by desaintmartin**
My previous PR introduced a wrongly-named file.

### CODE REVIEW

**Comment by cpanato** [comment]
@carlisia when you have time can you review this one and merge?

**Comment by cpanato** [comment]
Im going to merge this since is low impact. sorry if not correct. but would like to unblock other PR and not asking to much for rebase

**Comment by carlisia** [comment]
@desaintmartin oh noez, it will need another rebase!

**Comment by cpanato** [comment]
sorry for all back and forth 
thanks so much for your contribution

**Pull request merged**
