### PR TITLE
Add initial chart

### PR DESCRIPTION
**Pull request by cpanato**
- Migrate the Velero Helm Chart from `helm/charts` repo to new home
- add the github actions to Lint, Test and release the charts

### CODE REVIEW

**Comment by cpanato** [comment]
need to create a new branch callend `gh-pages` to host the charts and to the users can connect.

**Comment by cpanato** [comment]
I think we need to enable the github actions for this Repo, and maybe merge this and iterate over.

**Comment by carlisia** [comment]
This is the current setting for GH Actions, does it seem right?

image

**Comment by cpanato** [comment]
@carlisia yes, so I think to that work we need to have the action merged and configured

I will create another PR just to add the github action, what do you think?

**Comment by carlisia** [comment]
Yes, let's try that.

**Comment by cpanato** [comment]
here: https://github.com/vmware-tanzu/helm-charts/pull/11

**Comment by cpanato** [comment]
oh got merged :/ i was waiting for the github actions first then we can test the pipeline :)

**Comment by cpanato** [comment]
ok, no worries, i can open a new one to test it :) there are some steps to do

**Pull request merged**
