### PR TITLE
[velero] fix: remove check on CRDs availability

### LINKED ISSUE #388: ServiceMonitor Not Deploying
**What steps did you take and what happened:**
Deployed helm chart utilising argocd kustomize+helm with correct values:

    metrics:
      enabled: true
      scrapeInterval: 30s
      scrapeTimeout: 10s
    
      # service metdata if metrics are enabled
      service:
        annotations: {}
        labels: {}
    
      # Pod annotations for Prometheus
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/metrics"
    
      serviceMonitor:
        enabled: true
        additionalLabels: {}
        # ServiceMonitor namespace. Default to Velero namespace.
        namespace: velero

**What did you expect to happen:**
ServiceMonitor resource should be deployed however none is including when building manually.

**Anything else you would like to add:**
I suspect the issue is to do with the well-meaning capabilities check added 3 months ago to the ServiceMonitor template
`{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}`

I'd argue, particularly with the default having service monitor disabled, we realistically should be able to expect someone deploying the chart with it intentionally enabled to know if prometheus CRDs are already deployed, and to know how to resolve if they're not.

As a result and with incompatibility with common CI clients as well as manual builds, I believe this check should be removed.

### PR DESCRIPTION
**Pull request by tholander**
#### Special notes for your reviewer:

Fixes #388 

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Comment by jenting** [comment]
@tholander Could you amend the commit to add signoff-by? Thank you.

**Comment by jenting** [comment]
@ariep May I ask you to help review this PR?

**Comment by tholander** [comment]
@jenting yes, sorry I forgot to sign-off one commit. It should be ok now

**Review by jenting — APPROVED** [review]

**Comment by ariep** [comment]
> @ariep May I ask you to help review this PR?

Thanks for notifying me @jenting !

As you may have guessed, this PR would be a regression for our setup: some of our clusters have the monitoring API available and others do not, and that is a dynamic property so it's hard to predict for us if a given velero install should have the ServiceMonitor enabled. The "autodetect" that was introduced by this check is ideal for us. I would argue that it's also a good default, because presence of the monitoring API has a good chance of meaning you'll want to monitor velero as well, but opinions may differ on that of course. This does indeed assume that the check manages to get the right answer, which it unfortunately doesn't in the case of this issue.

@tholander I don't know if there's a way to modify your argocd setup and make the check work. If there isn't, then would it be an option to introduce another helm value -- or for example a third recognized value `autodetect` for the `enabled` one -- so that one may choose any of 1. force off (current `enabled: false`); 2. force on (your proposed `enabled: true`); and 3. switch on but only if API available (current `enabled: true`)? I personally don't mind so much what the default is, as long as it's possible to get the current "autodetect" behaviour with some (combination of) helm values.

**Comment by tholander** [comment]
is this condition. understandable enough ?
```yaml
{{ if and (and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled) (or (not .Values.metrics.autoDetect) (and .Values.metrics.serviceMonitor.autoDetect (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1"))) }}
```

**Comment by ariep** [comment]
@tholander Thanks for your quick reaction in the form of the new commit!

I think there's a typo here:
```
{{ if and (and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled) (or (not .Values.metrics.autoDetect) (and .Values.metrics.serviceMonitor.autoDetect (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1"))) }}
```
The first reference here to the new `autoDetect` variable misses the `serviceMonitor.` part. In fact I think the expression can be simplified slightly to
```
{{ if and (and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled) (or (not .Values.metrics.serviceMonitor.autoDetect) (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1")) }}
```

**Comment by tholander** [comment]
oh.. my bad, I'll fix that asap

**Comment by tholander** [comment]
it should be ok now. Thanks for noticing the typo, and your expression is indeed simpler!

**Comment by tholander** [comment]
@ariep is there still something blocking for approval ?

**Comment by ariep** [comment]
> @ariep is there still something blocking for approval ?

No, it looks good to me now, thanks! I don't have write permissions here though, I'm only an incidental contributor :). So I can't formally approve, that's up to the maintainers @jenting .

**Review by jenting — DISMISSED** [review]
Thank you all!

**Review by jenting — APPROVED** [review]

**Review by qiuming-best — APPROVED** [review]

**Pull request merged**
