### PR TITLE
Fix Helm 2 CRD generation

### PR DESCRIPTION
**Pull request by MrFreezeex**
Signed-off-by: Arthur Outhenin-Chalandre <arthur@cri.epita.fr>

I have this issue when I install the latest velero helm chart with ArgoCD:
```
rpc error: code = Unknown desc = Failed to unmarshal manifest: error unmarshaling JSON: Object 'Kind' is missing in '{"apiVersion":"apiextensions.k8s.io/v1beta1"}'
```

ArgoCD recognizes the velero chart as an helm2 chart and therefore uses the helm2 binary for it.
I tested and I saw that the line `apiVersion: apiextensions.k8s.io/v1beta1` is not indented correctly with helm2 (the output in helm3 is correct). This PR is fixing this indentation issue.

### CODE REVIEW

**Comment by MrFreezeex** [comment]
I bumped the chart version, should fix the CI.

**Comment by MrFreezeex** [comment]
I removed the leading whitespace on CRD that was used in the #125 to fix this issue.

**Comment by nrb** [comment]
@MrFreezeex CI had some intermittent failures with the AWS plugin installing, so I re-ran it. I don't think the whitespace removal is 100% necessary, but doesn't look like it hurts either.

**Comment by MrFreezeex** [comment]
> @MrFreezeex CI had some intermittent failures with the AWS plugin installing, so I re-ran it. I don't think the whitespace removal is 100% necessary, but doesn't look like it hurts either.

Yes I figured It out, I think It was kind of a hack to fix the chart in the previous PR.

**Comment by jenting** [comment]
> > @MrFreezeex CI had some intermittent failures with the AWS plugin installing, so I re-ran it. I don't think the whitespace removal is 100% necessary, but doesn't look like it hurts either.
> 
> Yes I figured It out by testing with kubectl, I think the leading line was kind of a hack to fix the chart in the previous PR (having the first empty line indented in every CRD).

Well, it's not hacking but directly copy from https://github.com/vmware-tanzu/velero/blob/v1.4.0/pkg/generated/crds/manifests/velero.io_backups.yaml, it includes the first empty line on all CRDs.

**Pull request merged**
