### PR TITLE
[velero] Release helm charts by github-actions

### LINKED ISSUE #20: Use a github token from a bot instead of the one for @carlisia
the token that is being used to release the charts (https://github.com/vmware-tanzu/helm-charts/releases) are from @carlisia a good practice is to use a bot github account, so we dont need to use personal tokens instead we use the token from the bot

/cc @carlisia @nrb

### PR DESCRIPTION
**Pull request by jenting**
#### Special notes for your reviewer:

fixes #20 
reference to https://github.com/helm/chart-releaser-action/tree/v1.0.0#example-workflow

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Comment by jenting** [comment]
I've tested it on my forked repository.

image

**Comment by mvisonneau** [comment]
beware that using fetch-depth: 0 on the checkout action messes up with the release action, I spent some time troubleshooting this myself: https://github.com/mvisonneau/helm-charts/commit/479468d7322f84d36821ef3b4328c9395498efd5

**Comment by jenting** [comment]
> beware that using fetch-depth: 0 on the checkout action messes up with the release action, I spent some time troubleshooting this myself: [mvisonneau/helm-charts@479468d](https://github.com/mvisonneau/helm-charts/commit/479468d7322f84d36821ef3b4328c9395498efd5)

thanks for the suggestion :bow:

**Review by carlisia — DISMISSED** [review]

**Review by carlisia — APPROVED** [review]
Thank you for this!

**Comment by carlisia** [comment]
If this works I'll delete the GH Token being used.

**Comment by carlisia** [comment]
@cpanato PTAL thanks.

**Review by cpanato — APPROVED** [review]
thanks!

**Comment by jenting** [comment]
> beware that using fetch-depth: 0 on the checkout action messes up with the release action, I spent some time troubleshooting this myself: [mvisonneau/helm-charts@479468d](https://github.com/mvisonneau/helm-charts/commit/479468d7322f84d36821ef3b4328c9395498efd5)

I think the `fetch-depth: 0` is needed when you use `actions/checkout@v2`, reference to https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602058369. Or you could choose another solution https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896.

**Comment by mvisonneau** [comment]
absolutely sorry about that 🤦 I just realised that as well..

**Pull request merged**
