### PR TITLE
[velero] Add option in values.yaml to customize secret name

### LINKED ISSUE #181: Add option in values.yaml to customize secret name
**Describe the problem/challenge you have**
If we install velero server via helm chart instead of velero cli, the secret name is `{{ include "velero.fullname" . }}`.
However, the vSphere plugin requires the secret with name `cloud-credentials`. Or the vSphere plugin installation will fail.

**Describe the solution you'd like**
Add option in values.yaml to configure secret name separately.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): 
v3.1.2
- helm chart version and app version:
  - helm2 (use `helm list`):
  - helm3 (use `helm list -n <YOUR NAMESPACE>`): velero-2.12.17
- Kubernetes version (use `kubectl version`): v1.16.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by csgtree**
#### Special notes for your reviewer:

fix #181

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Review by jenting — APPROVED** [review]
LGTM, thank you.

**Comment by cpanato** [comment]
@csgtree can you please rebase your PR and remove unnecessary commits and have only your change ? I see there is commits from other branches.

thanks

**Comment by jenting** [comment]
I think it's similar to #179.

**Comment by csgtree** [comment]
> I think it's similar to #179.

Will the two PR conflict or dup? If so, pick #179 and abandon this one.

**Comment by jenting** [comment]
> > I think it's similar to #179.
> 
> Will the two PR conflict or dup? If so, pick #179 and abandon this one.

From the issue description, it's a bit different. Or may I ask is #179 achievement could solve the issue you faced?

**Review by jenting — DISMISSED** [review]

**Review by cpanato — DISMISSED** [review]

**Review by jenting — APPROVED** [review]

**Review by cpanato — APPROVED** [review]

**Pull request merged**
