### PR TITLE
Add documentation for having separate providers

### PR DESCRIPTION
**Pull request by austinbv**
Documentation in the `values.yaml` to make clear having
separate providers for `volumeSnapshotLocation`,
`backupStorageLocation`, and the `deployment.yaml`

This fixes https://github.com/vmware-tanzu/helm-charts/pull/97#pullrequestreview-392313774

Signed-off-by: Austin Vance <austin@focusedlabs.io>

### CODE REVIEW

**Comment by skriss** [comment]
thanks for making these docs updates @austinbv! Looks like you'll need to rebase to pass required checks.

**Comment by austinbv** [comment]
Hmmm - this is rebased with the current master.

**Comment by skriss** [comment]
Looks like it might want you to increment the version #..

**Comment by austinbv** [comment]
> Looks like it might want you to increment the version #..

Done and done

**Comment by austinbv** [comment]
@skriss I bumped to v2.9.13 to allow the merge of #94 before this one

**Comment by skriss** [comment]
unfortunately you'll have to rebase again anyway. can you also remove the .patch file that got added? Thanks!

**Comment by austinbv** [comment]
> unfortunately you'll have to rebase again anyway. can you also remove the .patch file that got added? Thanks!

Good to go!

**Pull request merged**
