### PR TITLE
[velero] Use image tag 1.5 instead of 1.5.x

### PR DESCRIPTION
**Pull request by jenting**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Review by cpanato — APPROVED** [review]

**Comment by jenting** [comment]
@carlisia PTAL

**Review by carlisia — COMMENTED** [review]
Isn't the chart installing version 1.5.2 in specific?

https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml#L9

**Comment by jenting** [comment]
> Isn't the chart installing version 1.5.2 in specific?
> 
> 
> 
> https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml#L9

Yes, I think the values.yaml have specify the image tag, so I removed the helm install to specify which image tag to use.

Also, I update the link to velero.io to use 1.5 url, not 1.5.x

**Review by cpanato — CHANGES_REQUESTED** [review]
this file `charts/velero/^C` is needed?

**Review by cpanato — DISMISSED** [review]
thanks!

**Review by cpanato — APPROVED** [review]

**Review by carlisia — APPROVED** [review]
👍

**Pull request merged**
