### PR TITLE
[Velero] Fixing restic daemonset yaml

### PR DESCRIPTION
**Pull request by nirav-chotai**
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Comment by jenting** [comment]
@nirav-chotai thanks for your contribution, could you please elaborate more on the problem you met? Thanks.

**Comment by nirav-chotai** [comment]
@jenting , having duplicate values in restic daemonset leads to confusion and quotes are really not needed for setting environment variables.

**Review by jenting — DISMISSED** [review]
Thank you :+1:

**Review by jenting — APPROVED** [review]
LGTM, thanks ^^

**Comment by jenting** [comment]
I've help bump the chart version, PTAL @cpanato

**Review by cpanato — APPROVED** [review]

**Pull request merged**
