### PR TITLE
[velero] creds env from secret

### PR DESCRIPTION
**Pull request by Lirt**
#### Description

This PR enables creation of velero deployment with environment variables configured from secret by using `envFrom.secretRef`. This way of configuration is more secure than configuring environment variables directly with `env` (in case of this repository `credentials.extraEnvVars`).

This was done in order to enable users to securely configure environment variables for clouds such as Openstack, where authentication is most of the time configured differently (env vars) compared to clouds such as AWS, GCP, where secret is mounted from volume.

Example usage:

1. Create secret in velero namespace:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: openstack-credentials
  namespace: velero
type: Opaque
data:
  OS_PROJECT_DOMAIN_NAME: <base64_encoded_value>
  OS_USER_DOMAIN_NAME: <base64_encoded_value>
  OS_DOMAIN_NAME: <base64_encoded_value>
  OS_PROJECT_ID: <base64_encoded_value>
  OS_USERNAME: <base64_encoded_value>
  OS_PASSWORD: <base64_encoded_value>
  OS_AUTH_URL: <base64_encoded_value>
  OS_IDENTITY_API_VERSION: <base64_encoded_value>
  OS_IMAGE_API_VERSION: <base64_encoded_value>
```

2. Specify secret ref to previously created secret in helm chart values:

```yaml
---
...
...
credentials:
  extraSecretRef: "openstack-credentials"
...
...
```

Output of `kubectl describe deployment velero`:

```yaml
Pod Template:
  Containers:
   velero:
    Environment Variables from:
      openstack-credentials  Secret  Optional: false
```

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the ~~README.md~~ `values.yaml`
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Comment by jenting** [comment]
@Lirt Thanks for the PR, I think we could also add `envFrom.secretRef` to the `restic-daemonset.yaml`.

**Comment by Lirt** [comment]
Hello @jenting,

thank you for taking the review of this PR.

I also updated Restic DaemonSet, but I need some time to try it, because I don't use Restic in my environment.

**Comment by jenting** [comment]
> Hello @jenting,
> 
> thank you for taking the review of this PR.
> 
> I also updated Restic DaemonSet, but I need some time to try it, because I don't use Restic in my environment.

NP! I think there is possible that restic DaemonSet would reference env from secret.

**Review by jenting — APPROVED** [review]
LGTM

**Comment by Lirt** [comment]
Any update for review?

**Comment by jenting** [comment]
> Any update for review?

@carlisia @cpanato PTAL

**Review by cpanato — DISMISSED** [review]

**Review by jenting — APPROVED** [review]
I've helped to bump the chart version.

LGTM.

**Comment by jenting** [comment]
@cpanato PTAl again 🙏

**Comment by jenting** [comment]
I think it's similar to #184.

**Comment by Lirt** [comment]
@jenting This works so that cloud provider such as GCP which can read credentials from file will have the credentials file mounted in `/credentials`. Difference here is that it will configure environment variables from secret (because Openstack with gophercloud for example cannot read it from file)

- useSecret in template: https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/deployment.yaml#L123
- gophercloud docs: https://godoc.org/github.com/gophercloud/gophercloud#

**Review by cpanato — APPROVED** [review]

**Pull request merged**
