### PR TITLE
[velero] probes only when metrics are enabled

### PR DESCRIPTION
**Pull request by maxime1907**
#### Special notes for your reviewer:
Fixes https://github.com/vmware-tanzu/helm-charts/issues/470

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the values.yaml or README.md
- [x] Title of the PR starts with chart name (e.g. `[velero]`)

### CODE REVIEW

**Review by jenting — APPROVED** [review]

**Review by qiuming-best — APPROVED** [review]

**Review by jenting — CHANGES_REQUESTED** [review]
I think we should add 

```yaml
{{- if .Values.metrics.enabled }}
{{- end }}
```

between https://github.com/vmware-tanzu/helm-charts/blob/90450f6ea3448f987f6bb8e5d13491182718f755/charts/velero/templates/deployment.yaml#L157-L163

**Comment by maxime1907** [comment]
@jenting its done!

**Comment by jenting** [comment]
@maxime1907 Given the http-monitoring is valid when `.Values.metrics.enabled = true` https://github.com/vmware-tanzu/helm-charts/blob/90450f6ea3448f987f6bb8e5d13491182718f755/charts/velero/templates/deployment.yaml#L70-L74

So, we should change the deployment.yaml to

```yaml
          {{- if .Values.metrics.enabled }}
          {{- with .Values.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
```

**Comment by maxime1907** [comment]
@jenting is it ok now ?

**Review by jenting — COMMENTED** [review]
We don't need to change the values.yaml anymore.

**Review by jenting — APPROVED** [review]
Thank you 😊

**Review by qiuming-best — APPROVED** [review]

**Pull request merged**
